[2023-08-02T11:24:37.349-0500] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customoperator.Hello scheduled__2022-08-08T00:00:00+00:00 [queued]>
[2023-08-02T11:24:37.357-0500] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customoperator.Hello scheduled__2022-08-08T00:00:00+00:00 [queued]>
[2023-08-02T11:24:37.357-0500] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-02T11:24:37.372-0500] {taskinstance.py:1327} INFO - Executing <Task(HelloOperator): Hello> on 2022-08-08 00:00:00+00:00
[2023-08-02T11:24:37.377-0500] {standard_task_runner.py:57} INFO - Started process 108290 to run task
[2023-08-02T11:24:37.381-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'customoperator', 'Hello', 'scheduled__2022-08-08T00:00:00+00:00', '--job-id', '379', '--raw', '--subdir', 'DAGS_FOLDER/4.customOperator.py', '--cfg-path', '/tmp/tmpjmvaog30']
[2023-08-02T11:24:37.383-0500] {standard_task_runner.py:85} INFO - Job 379: Subtask Hello
[2023-08-02T11:24:37.425-0500] {task_command.py:410} INFO - Running <TaskInstance: customoperator.Hello scheduled__2022-08-08T00:00:00+00:00 [running]> on host pop-os.localdomain
[2023-08-02T11:24:37.493-0500] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customoperator' AIRFLOW_CTX_TASK_ID='Hello' AIRFLOW_CTX_EXECUTION_DATE='2022-08-08T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-08T00:00:00+00:00'
[2023-08-02T11:24:37.494-0500] {taskinstance.py:1824} ERROR - Task failed with exception
TypeError: HelloOperator.execute() got an unexpected keyword argument 'context'
[2023-08-02T11:24:37.497-0500] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=customoperator, task_id=Hello, execution_date=20220808T000000, start_date=20230802T162437, end_date=20230802T162437
[2023-08-02T11:24:37.633-0500] {standard_task_runner.py:104} ERROR - Failed to execute job 379 for task Hello (HelloOperator.execute() got an unexpected keyword argument 'context'; 108290)
[2023-08-02T11:24:37.674-0500] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-02T11:24:37.686-0500] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
