[2023-08-02T11:24:24.390-0500] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customoperator.Hello scheduled__2022-08-05T00:00:00+00:00 [queued]>
[2023-08-02T11:24:24.396-0500] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customoperator.Hello scheduled__2022-08-05T00:00:00+00:00 [queued]>
[2023-08-02T11:24:24.397-0500] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-02T11:24:24.413-0500] {taskinstance.py:1327} INFO - Executing <Task(HelloOperator): Hello> on 2022-08-05 00:00:00+00:00
[2023-08-02T11:24:24.421-0500] {standard_task_runner.py:57} INFO - Started process 108245 to run task
[2023-08-02T11:24:24.425-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'customoperator', 'Hello', 'scheduled__2022-08-05T00:00:00+00:00', '--job-id', '376', '--raw', '--subdir', 'DAGS_FOLDER/4.customOperator.py', '--cfg-path', '/tmp/tmp9kr6arf1']
[2023-08-02T11:24:24.427-0500] {standard_task_runner.py:85} INFO - Job 376: Subtask Hello
[2023-08-02T11:24:24.470-0500] {task_command.py:410} INFO - Running <TaskInstance: customoperator.Hello scheduled__2022-08-05T00:00:00+00:00 [running]> on host pop-os.localdomain
[2023-08-02T11:24:24.534-0500] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customoperator' AIRFLOW_CTX_TASK_ID='Hello' AIRFLOW_CTX_EXECUTION_DATE='2022-08-05T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-05T00:00:00+00:00'
[2023-08-02T11:24:24.535-0500] {taskinstance.py:1824} ERROR - Task failed with exception
TypeError: HelloOperator.execute() got an unexpected keyword argument 'context'
[2023-08-02T11:24:24.539-0500] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=customoperator, task_id=Hello, execution_date=20220805T000000, start_date=20230802T162424, end_date=20230802T162424
[2023-08-02T11:24:24.686-0500] {standard_task_runner.py:104} ERROR - Failed to execute job 376 for task Hello (HelloOperator.execute() got an unexpected keyword argument 'context'; 108245)
[2023-08-02T11:24:24.718-0500] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-02T11:24:24.731-0500] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
