[2023-08-02T11:24:19.531-0500] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customoperator.Hello scheduled__2022-08-04T00:00:00+00:00 [queued]>
[2023-08-02T11:24:19.541-0500] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customoperator.Hello scheduled__2022-08-04T00:00:00+00:00 [queued]>
[2023-08-02T11:24:19.541-0500] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-02T11:24:19.563-0500] {taskinstance.py:1327} INFO - Executing <Task(HelloOperator): Hello> on 2022-08-04 00:00:00+00:00
[2023-08-02T11:24:19.575-0500] {standard_task_runner.py:57} INFO - Started process 108234 to run task
[2023-08-02T11:24:19.580-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'customoperator', 'Hello', 'scheduled__2022-08-04T00:00:00+00:00', '--job-id', '375', '--raw', '--subdir', 'DAGS_FOLDER/4.customOperator.py', '--cfg-path', '/tmp/tmpwgg5zq2f']
[2023-08-02T11:24:19.583-0500] {standard_task_runner.py:85} INFO - Job 375: Subtask Hello
[2023-08-02T11:24:19.628-0500] {task_command.py:410} INFO - Running <TaskInstance: customoperator.Hello scheduled__2022-08-04T00:00:00+00:00 [running]> on host pop-os.localdomain
[2023-08-02T11:24:19.701-0500] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customoperator' AIRFLOW_CTX_TASK_ID='Hello' AIRFLOW_CTX_EXECUTION_DATE='2022-08-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-04T00:00:00+00:00'
[2023-08-02T11:24:19.702-0500] {taskinstance.py:1824} ERROR - Task failed with exception
TypeError: HelloOperator.execute() got an unexpected keyword argument 'context'
[2023-08-02T11:24:19.708-0500] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=customoperator, task_id=Hello, execution_date=20220804T000000, start_date=20230802T162419, end_date=20230802T162419
[2023-08-02T11:24:19.887-0500] {standard_task_runner.py:104} ERROR - Failed to execute job 375 for task Hello (HelloOperator.execute() got an unexpected keyword argument 'context'; 108234)
[2023-08-02T11:24:19.916-0500] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-02T11:24:19.940-0500] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
