[2023-08-02T11:24:28.768-0500] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: customoperator.Hello scheduled__2022-08-06T00:00:00+00:00 [queued]>
[2023-08-02T11:24:28.775-0500] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: customoperator.Hello scheduled__2022-08-06T00:00:00+00:00 [queued]>
[2023-08-02T11:24:28.775-0500] {taskinstance.py:1308} INFO - Starting attempt 1 of 1
[2023-08-02T11:24:28.793-0500] {taskinstance.py:1327} INFO - Executing <Task(HelloOperator): Hello> on 2022-08-06 00:00:00+00:00
[2023-08-02T11:24:28.801-0500] {standard_task_runner.py:57} INFO - Started process 108255 to run task
[2023-08-02T11:24:28.806-0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'customoperator', 'Hello', 'scheduled__2022-08-06T00:00:00+00:00', '--job-id', '377', '--raw', '--subdir', 'DAGS_FOLDER/4.customOperator.py', '--cfg-path', '/tmp/tmp18dei965']
[2023-08-02T11:24:28.808-0500] {standard_task_runner.py:85} INFO - Job 377: Subtask Hello
[2023-08-02T11:24:28.860-0500] {task_command.py:410} INFO - Running <TaskInstance: customoperator.Hello scheduled__2022-08-06T00:00:00+00:00 [running]> on host pop-os.localdomain
[2023-08-02T11:24:28.925-0500] {taskinstance.py:1545} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='customoperator' AIRFLOW_CTX_TASK_ID='Hello' AIRFLOW_CTX_EXECUTION_DATE='2022-08-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2022-08-06T00:00:00+00:00'
[2023-08-02T11:24:28.926-0500] {taskinstance.py:1824} ERROR - Task failed with exception
TypeError: HelloOperator.execute() got an unexpected keyword argument 'context'
[2023-08-02T11:24:28.930-0500] {taskinstance.py:1345} INFO - Marking task as FAILED. dag_id=customoperator, task_id=Hello, execution_date=20220806T000000, start_date=20230802T162428, end_date=20230802T162428
[2023-08-02T11:24:29.076-0500] {standard_task_runner.py:104} ERROR - Failed to execute job 377 for task Hello (HelloOperator.execute() got an unexpected keyword argument 'context'; 108255)
[2023-08-02T11:24:29.098-0500] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2023-08-02T11:24:29.119-0500] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
